on: push

name: Continuous integration

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-latest
        features:
          - openblas-src/static
          - openblas-src/system
    steps:
      - uses: actions/checkout@v2

      - uses: mstksg/get-package@v1
        with:
          brew: openblas
          apt-get: libopenblas-dev

      - uses: actions-rs/toolchain@v1
        name: Set up toolchain
        with:
          profile: minimal
          toolchain: 1.51.0
          override: true

      - uses: actions-rs/cargo@v1
        name: Run the main
        with:
          command: run
          args: --features ${{ matrix.features }}
